version: "2"

services:

  samba:
    image: dperson/samba:rpi
    restart: always
    command: '-u "pi;password" -s "media;/media;yes;no" -s "downloads;/downloads;yes;no"'
    stdin_open: true
    tty: true
    ports:
      - 139:130
      - 445:445
    volumes:
      - /usr/share/zoneinfo/America/Argentina/Mendoza:/etc/localtime
      - /home/pi/media:/media
      - /home/pi/downloads:/downloads

  rtorrent:
    image: linuxserver/rutorrent:48a6db4b-ls30
    ports:
      - 80:80
      - 51413:51413
      - 6881:6881/udp
    volumes:
      - /home/pi/torrents-config:/config
      - /home/pi/media:/home/pi/media
      - /home/pi/downloads:/downloads
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always

  plex:
    image: jaymoulin/plex:1.14.1
    ports:
      - 32400:32400
      - 33400:33400
    volumes:
      - /home/pi/plex:/root/Library/Application Support/Plex Media Server
      - /home/pi/media:/media
    restart: always
    network_mode: "host"
