include:
  - compose.networking.yml

services:

  samba:
    image: dperson/samba # no hay tag con versiones, solo latest
    restart: always
    command: '-u "${SAMBA_USER};${SAMBA_PASSWORD}" \
                  -s "media;/media;yes;no" \
                  -s "downloads;/downloads;yes;no"'
    stdin_open: true
    tty: true
    environment:
      - TZ=${TZ}
    ports:
      - 139:139
      - 445:445
    volumes:
      - ${MEDIA}:/media
      - ${STORAGE}/torrents:/downloads
    networks:
      - lan
  plex:
    image: jaymoulin/plex:1.30.1.6562
    expose:
      - 32400
      - 33400
    # Descomentar si NO usas network_mode: "host"
    ports:
      - 32400:32400
      - 33400:33400
    environment:
      - TZ=${TZ}
    volumes:
      - ${STORAGE}/Plex Media Server:/root/Library/Application Support/Plex Media Server
      - ${MEDIA}:/media
      - ${STORAGE}/tmp:/tmp
    restart: unless-stopped

    networks:
      - lan
  transmission:
    image : jaymoulin/transmission:3.00-1.6.1
    command: transmission-daemon -f -g /config
    volumes:
      - ./transmission:/config
      - ${STORAGE}/torrents:/downloads
    ports:
      - {TRANSMISSION_PORT_UI}:9091
      - 51413:51413
      - 51413:51413/udp
    expose:
      - {TRANSMISSION_PORT_UI}
    restart: unless-stopped
    networks:
      - lan

  flexget:
    image: wiserain/flexget:3.5
    volumes:
      - ./flexget:/config
      - ./flexget/custom-cont-init.d:/custom-cont-init.d
      - ${STORAGE}/torrents:/downloads
      - ${MEDIA}:/storage
    ports:
      - ${FLEXGET_PORT}:5050
    environment:
      - PUID=1001
      - PGID=1001
      - TORRENT_PLUGIN=transmission
      - FG_WEBUI_PASSWD=${FLEXGET_PASSWORD} # la puedes cambiar por la que quieras
    restart: unless-stopped
    networks:
      - lan
